[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.111.0"
boto3 = "^1.34.142"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
